language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install

after_success:
  - more settings.xml
  - mvn deploy -q --settings settings.xml

notifications:
  email:
  - herve.tchepannou@gmail.com
